#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Controllers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROYECTO")]
	public partial class bdproyectoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public bdproyectoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PROYECTOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public bdproyectoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdproyectoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdproyectoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public bdproyectoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleados
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Entidad> Entidads
		{
			get
			{
				return this.GetTable<Entidad>();
			}
		}
		
		public System.Data.Linq.Table<Habitacion> Habitacions
		{
			get
			{
				return this.GetTable<Habitacion>();
			}
		}
		
		public System.Data.Linq.Table<Pai> Pais
		{
			get
			{
				return this.GetTable<Pai>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Personas
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Tipo> Tipos
		{
			get
			{
				return this.GetTable<Tipo>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InPersona")]
		public int InPersona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocId", DbType="VarChar(50)")] string docId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApPat", DbType="VarChar(50)")] string apPat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApMat", DbType="VarChar(50)")] string apMat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoDoc", DbType="VarChar(50)")] string tipoDoc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodPais", DbType="VarChar(50)")] string codPais, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="VarChar(50)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechNac", DbType="Date")] System.Nullable<System.DateTime> fechNac)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), docId, nombre, apPat, apMat, tipoDoc, codPais, ciudad, telefono, email, direccion, fechNac);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ins_cli_p")]
		public int Ins_cli_p([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string am, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string di, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ciu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string e, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, ap, am, di, tp, cp, ciu, tel, e, dir, fn);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Ins_emp_p")]
		public int Ins_emp_p([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string am, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string di, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ciu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tel, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string e, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ca, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, ap, am, di, tp, cp, ciu, tel, e, dir, fn, ca, tu);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente
	{
		
		private string _CodCli;
		
		public Cliente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCli", DbType="VarChar(50)")]
		public string CodCli
		{
			get
			{
				return this._CodCli;
			}
			set
			{
				if ((this._CodCli != value))
				{
					this._CodCli = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado
	{
		
		private string _CodEmp;
		
		private string _Cargo;
		
		private string _Turno;
		
		public Empleado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEmp", DbType="VarChar(250)")]
		public string CodEmp
		{
			get
			{
				return this._CodEmp;
			}
			set
			{
				if ((this._CodEmp != value))
				{
					this._CodEmp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(50)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="VarChar(50)")]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this._Turno = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entidad")]
	public partial class Entidad
	{
		
		private string _Nombre;
		
		private string _Nit;
		
		private System.Nullable<int> _Telefono;
		
		private string _Email;
		
		private int _CodPais;
		
		private string _Ciudad;
		
		private string _Tipo_de_pago;
		
		public Entidad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nit", DbType="VarChar(50)")]
		public string Nit
		{
			get
			{
				return this._Nit;
			}
			set
			{
				if ((this._Nit != value))
				{
					this._Nit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int")]
		public System.Nullable<int> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPais", DbType="Int NOT NULL")]
		public int CodPais
		{
			get
			{
				return this._CodPais;
			}
			set
			{
				if ((this._CodPais != value))
				{
					this._CodPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(50)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_de_pago", DbType="VarChar(50)")]
		public string Tipo_de_pago
		{
			get
			{
				return this._Tipo_de_pago;
			}
			set
			{
				if ((this._Tipo_de_pago != value))
				{
					this._Tipo_de_pago = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Habitacion")]
	public partial class Habitacion
	{
		
		private string _CodTip;
		
		private string _CodHab;
		
		private System.Nullable<float> _Precio;
		
		private string _Descripcion;
		
		private string _Estado;
		
		public Habitacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTip", DbType="VarChar(50)")]
		public string CodTip
		{
			get
			{
				return this._CodTip;
			}
			set
			{
				if ((this._CodTip != value))
				{
					this._CodTip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHab", DbType="VarChar(50)")]
		public string CodHab
		{
			get
			{
				return this._CodHab;
			}
			set
			{
				if ((this._CodHab != value))
				{
					this._CodHab = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Real")]
		public System.Nullable<float> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pais")]
	public partial class Pai
	{
		
		private int _CodPais;
		
		private string _Nombre;
		
		private string _SisMone;
		
		private string _Moneda;
		
		private System.Nullable<float> _TipoCambio;
		
		public Pai()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPais", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CodPais
		{
			get
			{
				return this._CodPais;
			}
			set
			{
				if ((this._CodPais != value))
				{
					this._CodPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SisMone", DbType="VarChar(50)")]
		public string SisMone
		{
			get
			{
				return this._SisMone;
			}
			set
			{
				if ((this._SisMone != value))
				{
					this._SisMone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(50)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCambio", DbType="Real")]
		public System.Nullable<float> TipoCambio
		{
			get
			{
				return this._TipoCambio;
			}
			set
			{
				if ((this._TipoCambio != value))
				{
					this._TipoCambio = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona
	{
		
		private string _Nombre;
		
		private string _ApPat;
		
		private string _ApMat;
		
		private string _DocId;
		
		private string _TipoDoc;
		
		private System.Nullable<int> _CodPais;
		
		private string _Ciudad;
		
		private System.Nullable<int> _Telefono;
		
		private string _Email;
		
		private string _Direccion;
		
		private System.Nullable<System.DateTime> _FechNac;
		
		public Persona()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApPat", DbType="VarChar(50)")]
		public string ApPat
		{
			get
			{
				return this._ApPat;
			}
			set
			{
				if ((this._ApPat != value))
				{
					this._ApPat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApMat", DbType="VarChar(50)")]
		public string ApMat
		{
			get
			{
				return this._ApMat;
			}
			set
			{
				if ((this._ApMat != value))
				{
					this._ApMat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocId", DbType="VarChar(50)")]
		public string DocId
		{
			get
			{
				return this._DocId;
			}
			set
			{
				if ((this._DocId != value))
				{
					this._DocId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDoc", DbType="VarChar(50)")]
		public string TipoDoc
		{
			get
			{
				return this._TipoDoc;
			}
			set
			{
				if ((this._TipoDoc != value))
				{
					this._TipoDoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPais", DbType="Int")]
		public System.Nullable<int> CodPais
		{
			get
			{
				return this._CodPais;
			}
			set
			{
				if ((this._CodPais != value))
				{
					this._CodPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(50)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int")]
		public System.Nullable<int> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechNac", DbType="Date")]
		public System.Nullable<System.DateTime> FechNac
		{
			get
			{
				return this._FechNac;
			}
			set
			{
				if ((this._FechNac != value))
				{
					this._FechNac = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo")]
	public partial class Tipo
	{
		
		private string _CodTip;
		
		private string _Nombre;
		
		public Tipo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTip", DbType="VarChar(50)")]
		public string CodTip
		{
			get
			{
				return this._CodTip;
			}
			set
			{
				if ((this._CodTip != value))
				{
					this._CodTip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario
	{
		
		private string _CodUs;
		
		private string _Pass;
		
		public Usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUs", DbType="VarChar(250)")]
		public string CodUs
		{
			get
			{
				return this._CodUs;
			}
			set
			{
				if ((this._CodUs != value))
				{
					this._CodUs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
